server:
  port: 4040
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dtms
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
#  thymeleaf:
#    prefix: classpath:/templates/
